### PR TITLE
Attempt ServerName replacements through Refaster

### PR DESCRIPTION
**Pull request by timtebeek**
## What's changed?
Make the ServerName getDisplayName and getFullName replacements from a Refaster recipe.

## What's your motivation?
Simpler to develop and maintain, as recipe generation is delegated to an annotation processor.

## Anything in particular you'd like reviewers to focus on?
Would this be acceptable to remove the `ChangeMethodInvocation`?

## Have you considered any alternatives or workarounds?
The ServerName recipes can also be handled by composition of one new recipe to add a String literal argument to a method invocation, and the existing `ChangeMethodTargetToStatic` + `ChangeType` recipes.

## Any additional context
https://github.com/openrewrite/rewrite-templating

### CODE REVIEW

**Comment by timtebeek** [comment]
Alternatively we can take the generated recipe and just use Method matchers to still replace `ChangeMethodInvocation`, which could still simplify the implementation quite a bit.

**Comment by knutwannheden** [comment]
> @knutwannheden somehow the `JavaTemplate.matcher()` does not find a match, despite seemingly the same types in use; does that not (yet?) work for zero-argument lambdas? Or is there a classloading issue with ServerName not yet in a dependency jar?

I didn't see any lambdas in the tests. Where are they?

Have you verified that the type attribution of the input sources is complete? Otherwise I would have to debug this.

**Comment by timtebeek** [comment]
OK good to know; not a high priority item here, as we can also continue with #5 for now; would you want me to log an issue against openrewrite/rewrite, assuming there's a matching issue there? Or would you first want to rule out any issues generating recipes in openrewrite/rewrite-templating?

**Comment by timtebeek** [comment]
We've gone with #5 for this repository; so I'll close this issue here. We can see if the problem recurs whenever we next try to match a lambda without arguments.

**Pull request closed without merging**
